services:
  dev:
    build:
      context: Dockerfile.d/dev
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    command:
      - bash
      - -c
      - |
        npm install
        npm run dev
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:3000:3000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/workspace
    working_dir: /workspace
version: "3.7"
